databases:
  - name: stocktrading-app-db
    databaseName: stocktrading_app
    user: stocktrading_app

services:
  - type: web
    name: stocktrading-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocktrading-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
